cc_binary(
        name = "jack-aec",
        deps = [
                "@libjack//:libjack",
                "@absl//absl/flags:flag",
                "@absl//absl/flags:parse",
                "@absl//absl/flags:usage",
                ],
        srcs = ["main.cc"]
        )
